name: helsinki_earnings
version: "1.0.0"
config-version: 2
profile: helsinki_earnings
model-paths: ["models"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages"]

models:
  helsinki_earnings:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

